name: plat_app
description: Plat App project.
publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # Flutter map, latlng
  cached_network_image: ^3.2.2
  badges: ^2.0.3
  google_maps_flutter: ^2.2.0
  get: ^4.6.5
  permission_handler: ^10.0.0
  smooth_page_indicator: ^1.0.0+2
  percent_indicator: ^4.2.2
  intl: ^0.17.0
  google_map_polyline_new: ^0.3.0+2
  camera: ^0.10.0+1
  location: ^4.4.0
  convex_bottom_bar: ^3.1.0+1
  flutter_native_image: ^0.0.6+1
  draggable_fab: ^0.1.4
  flutter_local_notifications: ^11.0.1
  shimmer: ^2.0.0
  qr_flutter: ^4.0.0
  device_info_plus: ^4.0.0
  webview_flutter: ^2.8.0
  package_info_plus: ^1.4.2
  url_launcher: ^6.0.20
  confetti: ^0.7.0
  image_picker: ^0.8.6
  map_launcher: ^2.4.0
  geolocator: ^9.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_analytics: ^10.0.7
  firebase_messaging: ^14.1.4
  firebase_remote_config: ^3.0.7
  change_app_package_name: ^1.1.0
  qr_code_scanner: ^1.0.1
  like_button: ^2.0.5
  bubble_tab_indicator: ^0.1.6
  photo_view: ^0.14.0
  google_fonts: ^4.0.3
  modal_bottom_sheet: ^2.1.2
  timelines: ^0.1.0
  dotted_line: ^3.1.0
  share_plus:
  animated_text_kit: ^4.2.2
  stretchy_header: ^2.0.0
  just_the_tooltip: ^0.0.12
  simple_gradient_text: ^1.2.4
  shared_preferences: ^2.2.0
  table_calendar:
  date_count_down:
  top_snackbar_flutter: ^3.1.0
  card_swiper: ^3.0.1
  appinio_swiper: ^2.0.2
  tab_container: ^2.0.0
  # flutter_pdfview: ^1.2.1

dependency_overrides:
  firebase_core_platform_interface: 4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Date format
  get_storage: ^2.0.3
  flutter_dotenv: ^5.0.2
  flutter_html: ^2.2.1
  flutter_inappwebview: ^5.7.2+2
  uni_links: ^0.5.1
  flutter_staggered_grid_view: ^0.6.1
  webviewx: ^0.2.1
  highlight_text: ^1.4.1
  twitter_login: ^4.2.3

  # firebase & auth
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1
  sign_in_with_apple: ^4.1.0
  otp_text_field: ^1.1.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/images/background_event.gif
    - assets/images/done.gif
    - assets/images/sending.gif
    - assets/images/loading.gif
    - .env
    - .env.development
    - .env.production
    - .env.staging
    - .env.store

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/avenir_next/AvenirNextLTPro-Regular.otf
          weight: 400
        - asset: assets/fonts/avenir_next/AvenirNextLTPro-Medium.otf
          weight: 500
        - asset: assets/fonts/avenir_next/AvenirNextLTPro-Demi.otf
          weight: 600
        - asset: assets/fonts/avenir_next/AvenirNextLTPro-Bold.otf
          weight: 700
    - family: Termina
      fonts:
        - asset: assets/fonts/termina/TerminaTest-Regular.otf
          weight: 400
        - asset: assets/fonts/termina/TerminaTest-Medium.otf
          weight: 500
        - asset: assets/fonts/termina/TerminaTest-Demi.otf
          weight: 600
        - asset: assets/fonts/termina/TerminaTest-Bold.otf
          weight: 700