// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh3wjnHqKzd-OqKD-5_jRjOHkxpZqYEec',
    appId: '1:1001974802677:android:f75f64d27d4d2228e97dbc',
    messagingSenderId: '1001974802677',
    projectId: 'plats-a05f3',
    storageBucket: 'plats-a05f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAiCmuaMfyaDXMEbYU_TyF8uNsOI7vSU',
    appId: '1:1001974802677:ios:616e8d5b6d6b160ee97dbc',
    messagingSenderId: '1001974802677',
    projectId: 'plats-a05f3',
    storageBucket: 'plats-a05f3.appspot.com',
    androidClientId: '1001974802677-014eq58hv1b57n7lf3bpa0c5b26sn6ej.apps.googleusercontent.com',
    iosClientId: '1001974802677-531rr8k23t1a75mrstuvv0h2pfck101n.apps.googleusercontent.com',
    iosBundleId: 'network.plats.action',
  );
}
