const Map<String, String> en = {
  'app_name': 'Plats',
  'email': 'Email',
  'password': 'Password',
  'remember': 'Remember',
  'forgot_password': 'Forgot password',
  'login': 'Login',
  'term_of_use': 'Term of use',
  'privacy_policy': 'Privacy policy',
  'languages': 'Languages',
  'invalid_email': 'Email address is invalid',
  'email_required': 'Email address is a required field',
  'invalid_password': 'Invalid password',
  'plats_network': '''PLATS
NETWORK''',
  'time_remaining': 'Time Remaining',
  'password_must_be_at_least_8_characters':
      'Password must be at least 8 characters',
  'invalid_confirm_password': 'Confirm password does not match',
  'invalid_full_name': 'Full name is a required field',
  'full_name': 'Full name',
  'or_sign_in_with': 'Or Sign in with',
  'create_a_new_account': 'Create a new account',
  'register': 'Register',
  'lets_sign_you_in': 'Let\'s sign you in',
  'fullname': 'Full name',
  'confirm_password': 'Password confirmation',
  'i_agree_with_the_plats_network': 'I agree with the Plats Network',
  'terms_of_service': 'Terms of Service',
  'password_not_match': 'Password does not match',
  'please_accept_terms_and_conditions':
      'Please accept terms and conditions to continue',
  'registered_email_address': 'Registered email address',
  'enter_your_email': 'Enter your email',
  'cancel': 'Cancel',
  'reset_password': 'Reset Password',
  'forgot_password_success_text':
      'A confirmation link has been sent to your email address. Please check and follow the detailed instructions.',
  'have_not_received_yet': 'Have not received yet?',
  'resend': 'Resend',
  'confirm': 'Confirm',
  'otp_verification': 'OTP Verification',
  'please_enter_the_otp': 'Please enter the OTP',
  'check_in': 'Check-in',
  'username_or_password_is_incorrect':
      'Username or Password is incorrect.\nPlease try again.',
  'try_again': 'Try again',
  'login_failed': 'Login failed',
  'congratulations': 'Congratulations!',
  'congratulations_text':
      'You have completed the mission and received the following rewards',
  'see_details': 'See details',
  'mystery_box': 'Mystery box',
  'voucher': 'Voucher',
  'back_to_task_pool': 'Back to Task Pool',
  'assets': 'Assets',
  'unread': 'Unread',
  'all': 'All',
  'new_tasks': 'New Tasks',
  'unbox': 'Unbox',
  'notification': 'Notification',
  'check_valid_photos': 'How to check your valid photos',
  'face_clearly_fully': 'Your face is clearly and fully captured.',
  'brand_logo_included': 'The brand\'s logo is included.',
  'not_use_bokeh_effect': 'Do not use bokeh effect while checking in.',
  'got_it': 'Got it',
  're_take': 'Re-take',
  'send': 'Send',
  'hello': 'Hello,',
  'see_more': 'See more',
  'hot_task': 'Hot Task',
  'task_in_progress': 'Task in progress',
  'back_to_task': 'Back to task',
  'searching_for': 'Searching for...',
  'more': 'More',
  'show_less': 'Show less',
  'schedule': 'Schedule',
  'checkin_help_text': 'Check-in address is available as follow as the ',
  'branch_list': 'branch list',
  'of': 'of',
  'start_now': 'Start now',
  'reward': 'Reward',
  'overview': 'Overview',
  'wait_to_unbox': 'Wait to unbox!',
  'your_mystery_box_including':
      'Your Mystery Box including rewards will be soon unboxed. Wait and see in the due time.',
  'unbox_schedule': 'Unbox Schedule',
  'days': 'DAYS',
  'hours': 'HOURS',
  'minutes': 'MINUTES',
  'ready_to_unbox': 'Ready to unbox!',
  'error': 'Error',
  'go_back': 'Go back',
  'done': 'Done',
  'by': 'By',
  'fetching_distance': 'Fetching distance...',
  'checkin': 'Checkin',
  'task_already_started1': 'You’re doing the  ',
  'task_already_started2':
      ' task. Do you really want to cancel and do this task?',
  'start_task_error': 'Start task error',
  'agree': 'Agree',
  'home': 'Home',
  'task_pool': 'Task Pool',
  'groups': 'Groups',
  'settings': 'Settings',
  'canceling_your_task': 'Canceling your task',
  'are_you_sure_cancel_task':
      'Are you sure to cancel this task?\nYou will not receive the rewards until you restart it. ',
  'yes': 'Yes',
  'no': 'No',
  'continue': 'Continue',
  'balance': 'Balance',
  'exchange_to_usdt_now': 'Exchange to USDT now',
  'claim_to_plats_wallet': 'Claim to Plats Wallet',
  'donate_to_friend': 'Donate to friend',
  'no_transactions_in_your_history_yet': 'No transactions in your history yet',
  'history': 'History',
  'lock_tray': 'Lock Tray',
  'main_tray': 'Main Tray',
  'send_to_main_tray': 'Send to Main Tray',
  'unlocked': 'Unlocked',
  'to_unlock': 'To unlock',
  'token': 'Token',
  'nft': 'NFT',
  'vouchers': 'Vouchers',
  'boxes': 'Boxes',
  'wallet': 'Wallet',
  'coming_soon': 'Coming soon',
  'no_more_data': 'No more data',
  'password_and_security': 'Password and security',
  'help_center': 'Help center',
  'about_app': 'About App',
  'refer_friends': 'Refer friends',
  'logout': 'Logout',
  'refer_us_to_your_friend': 'Refer us to your friend',
  'as_a_thank_you':
      'As a thank you, we’ll give you a big gift when when you invite 5 friends to join the program.',
  'join_now': 'Join Now',
  'change_password': 'Change password',
  'all_tasks': 'All Tasks',
  'video': 'Video',
  'install_app': 'Install App',
  'apply_now': 'Apply Now',
  'detail': 'Detail',
  'used': 'Used',
  'expired': 'Expired',
  'hurray_your_rewards_are_available_now':
      'Hurray! Your rewards are available now.\nLet’s see what you got (below).',
  'back_to_asset': 'Back to assets',
  'date_of_birth_placeholder': '29221',
  'date_of_birth': 'Date of birth',
  'sex': 'Sex',
  'save': 'Save',
  'edit_profile': 'Edit profile',
  'leave_app': 'Leave app?',
  'change_you_made': 'Changes you made may not be saved.',
  'leave': 'Leave',
  'password_to_secure':
      'Password to secure your account & verify when doing transactions. ',
  'enter_current_password': 'Enter current password',
  'enter_new_password': 'Enter new password',
  'confirm_new_password': 'Comfirm new password',
  'must_match_previous': 'Must match the previous entry',
  'successful': 'SUCCESSFUL',
  'your_password_changed': 'Your password has been changed!',
  'back_to_home': 'Back to Home',
  'back_to_login': 'Back to Login',
  'email_not_found': 'The email you entered is not found',
  'invalid_otp': 'Invalid OTP',
  'no_tray_item': 'You haven’t had any assets yet.',
  'male': 'Male',
  'female': 'Female',
  'other': 'Other',
  'invalid_credentials': 'These credentials do not match our records',
  'expiry_date': 'Expiry date: ',
  'please_login_with_social_network': 'Please login with Social Network',
  'no_gift': 'You haven\'t had any Gifts yet',
  'no_used_gifts': 'You haven\'t had any history of used items',
  'no_expired_gifts': 'You haven\'t had any expired items',
  'no_box': 'You haven\'t had any Boxes yet',
  'please_check_your_email_and_confirmation_code_again':
      'Please check your email and confirmation code again',
  'register_failed': 'Register failed',
  'update': 'Update',
  'task_time_out_title': 'Task timeout',
  'task_time_out_content': 'Your task is timed out',
  'close': 'Close',
  'box_is_already_opened': 'This box is already opened',
  'item_has_been_send_to_main_tray': 'The item has been send to main tray',
  'success': 'Success',
  'request_location_permission': 'Request location permission',
  'app_collects_location_data':
      'Plats Network app collects location data to provide Checkin Task function',
  'ok': 'Ok',
  'we_have_sent_an_email_please_check_your_email':
      'We have sent an email please check your email',
  'user_cancel_login': 'User cancel login',
  'login_error': 'Login error',
  'others': 'Others',
  'no_items': 'No items',
  'please_check_internet': 'Please check your internet connection',
  'gift': 'Gift',
  'open_the_box_now': 'Open the box now',
  'avatar': 'Avatar',
  'take_a_photo': 'Take a photo',
  'choose_from_library': 'Choose from library ',
  'please_enter_your_name': 'Please enter your name',
  'please_wait': 'Please wait',
  'your_information_has_been_updated':
      'Your information has been successfully updated.',
  'otp_sent': 'OTP sent',
  'website': 'Website',
  'social': 'Social',
  'description': 'Description',
  'password_validation_not_match': 'Password not matched.',
  'password_validation_8_characters':
      'Password must contain at least eight characters.',
  'password_validation_upper_lower':
      'Password must contain at least one uppercase and one lowercase letter',
  'password_validation_special_character':
      'Password must contain at least one symbol.',
  'password_validation_number': 'Password must contain at least one number.',
  'social_task': 'Social Task',
  'social_tasks': 'Social Tasks',
  'check_in_tasks': 'Check-in Tasks',
  'follow': 'Follow',
  'social_twitter_help_text':
      'Connect your Twitter account to verify Twitter actions in 1 click. \nWe will not post without your permission.',
  'connect_your_twitter_account': 'Connect your Twitter',
  'start_task_success': 'Start task success',
  'twitter_account_connected': 'Twitter account connected',
  'submit': 'Submit',
  'social_task_submit_success': 'Social task submit success',
  'connect_twitter_success': 'Connect Twitter success',
  'connect_twitter_error': 'Twitter id is already used',
  'go_to_assets': 'Go to Assets',
  'task_list': 'Task List',
  'plats_network_points': 'Plats Network Points',
  'delete_account': 'Delete account',
  'delete_account_help_text':
      'Are you sure you want to delete your account?\nThis will permanently delete your account and all of your data. \nYou will not be able to recover your account.',
  'fail_to_delete_account': 'Fail to delete account',
  'PSP': 'PSP',
  'checking_action': 'Checking action',
  'prize': 'Prize',
  'gender': 'Gender',
  'details': 'Details',
  'my_group': 'My Groups',
  'like': 'Like',
  'unlike': 'UnLike',
  'pin': 'Pin',
  'unpin': 'UnPin',
  'share': 'Share',
  'congratulations_you_have_received': 'Congratulations, you’ve got',
};
