const Map<String, String> vi = {
  'app_name': 'Plats',
  'email': 'Email',
  'password': 'Mật khẩu',
  'remember': 'Ghi nhớ',
  'forgot_password': 'Quên mật khẩu',
  'login': 'Đăng nhập',
  'term_of_use': 'Điều khoản sử dụng',
  'privacy_policy': 'Quyền riêng tư',
  'languages': 'Ngôn ngữ',
  'invalid_email': 'Vui lòng nhập Địa chỉ email',
  'invalid_password': 'Mật khẩu không hợp lệ',
  'plats_network': '''PLATS
NETWORK''',
  'time_remaining': 'Time Remaining',
  'email_required': 'Vui lòng nhập địa chỉ email',
  'password_must_be_at_least_8_characters': 'Mật khẩu cần ít nhất 8 ký tự',
  'invalid_confirm_password': 'Mật khẩu xác nhận không khớp',
  'invalid_full_name': 'Vui lòng nhập họ và tên',
  'full_name': 'Họ và tên',
  'or_sign_in_with': 'Hoặc đăng nhập bằng',
  'create_a_new_account': 'Tạo tài khoản mới',
  'register': 'Đăng ký',
  'lets_sign_you_in': 'Đăng nhập',
  'fullname': 'Họ và tên',
  'confirm_password': 'Xác nhận mật khẩu',
  'i_agree_with_the_plats_network': 'Tôi đồng ý với Plats Network',
  'terms_of_service': 'Điều khoản sử dụng',
  'password_not_match': 'Mật khẩu không khớp',
  'please_accept_terms_and_conditions':
      'Vui lòng đồng ý với điều khoản sử dụng để tiếp tục',
  'registered_email_address': 'Địa chỉ email đã đăng ký',
  'enter_your_email': 'Nhập địa chỉ email',
  'cancel': 'Hủy',
  'reset_password': 'Đặt lại mật khẩu',
  'forgot_password_success_text':
      'Một liên kết xác nhận đã được gửi đến địa chỉ email của bạn. Vui lòng kiểm tra và làm theo các hướng dẫn để khôi phục mật khẩu.',
  'have_not_received_yet': 'Chưa nhận được?',
  'resend': 'Gửi lại',
  'confirm': 'Xác nhận',
  'otp_verification': 'Xác minh OTP',
  'please_enter_the_otp': 'Vui lòng nhập OTP',
  'check_in': 'Check-in',
  'username_or_password_is_incorrect':
      'Tên đăng nhập hoặc mật khẩu không chính xác.\nVui lòng thử lại.',
  'try_again': 'Thử lại',
  'login_failed': 'Đăng nhập thất bại',
  'congratulations': 'Chúc mừng',
  'congratulations_text':
      'Bạn đã hoàn thành nhiệm vụ và nhận được các phần thưởng sau',
  'see_details': 'Xem chi tiết',
  'mystery_box': 'Hộp bí ẩn',
  'voucher': 'Voucher',
  'back_to_task_pool': 'Quay lại Task Pool',
  'assets': 'Tài sản',
  'unread': 'Chưa đọc',
  'all': 'Tất cả',
  'new_tasks': 'Nhiệm vụ mới',
  'unbox': 'Chưa đọc',
  'notification': 'Thông báo',
  'check_valid_photos': 'How to check your valid photos',
  'face_clearly_fully': 'Your face is clearly and fully captured.',
  'brand_logo_included': 'The brand\'s logo is included.',
  'not_use_bokeh_effect': 'Do not use bokeh effect while checking in.',
  'got_it': 'Got it',
  're_take': 'Re-take',
  'send': 'Send',
  'hello': 'Hello,',
  'see_more': 'See more',
  'hot_task': 'Hot Task',
  'task_in_progress': 'Task in progress',
  'back_to_task': 'Back to task',
  'searching_for': 'Searching for...',
  'more': 'More',
  'show_less': 'Show less',
  'schedule': 'Lịch trình',
  'checkin_help_text': 'Check-in address is available as follow as the ',
  'branch_list': 'branch list',
  'of': 'of',
  'start_now': 'Bắt đầu ngay',
  'reward': 'Phần thưởng',
  'overview': 'Tổng quan',
  'wait_to_unbox': 'Wait to unbox!',
  'your_mystery_box_including':
      'Your Mystery Box including rewards will be soon unboxed. Wait and see in the due time.',
  'unbox_schedule': 'Unbox Schedule',
  'days': 'DAYS',
  'hours': 'HOURS',
  'minutes': 'MINUTES',
  'ready_to_unbox': 'Ready to unbox!',
  'error': 'Lỗi',
  'go_back': 'Quay lại',
  'done': 'Done',
  'by': 'Bởi',
  'fetching_distance': 'Đang tìm khoảng cách...',
  'checkin': 'Checkin',
  'task_already_started1': 'You’re doing the  ',
  'task_already_started2':
      ' task. Do you really want to cancel and do this task?',
  'agree': 'Đồng ý',
  'start_task_error': 'Bắt đầu nhiệm vụ thất bại',
  'home': 'Home',
  'task_pool': 'Task Pool',
  'groups': 'Groups',
  'settings': 'Settings',
  'canceling_your_task': 'Canceling your task',
  'are_you_sure_cancel_task':
      'Are you sure to cancel this task?\nYou will not receive the rewards until you restart it. ',
  'yes': 'Yes',
  'no': 'No',
  'continue': 'Continue',
  'balance': 'Số dư',
  'exchange_to_usdt_now': 'Đổi sang USDT ngay',
  'claim_to_plats_wallet': 'Claim to Plats Wallet',
  'donate_to_friend': 'Donate to friend',
  'no_transactions_in_your_history_yet': 'No transactions in your history yet',
  'history': 'Lịch sử',
  'lock_tray': 'Lock Tray',
  'main_tray': 'Main Tray',
  'send_to_main_tray': 'Send to Main Tray',
  'unlocked': 'Unlocked',
  'to_unlock': 'To unlock',
  'token': 'Token',
  'nft': 'NFT',
  'vouchers': 'Vouchers',
  'boxes': 'Boxes',
  'wallet': 'Wallet',
  'coming_soon': 'Coming soon',
  'no_more_data': 'No more data',
  'password_and_security': 'Password and security',
  'help_center': 'Help center',
  'about_app': 'About App',
  'refer_friends': 'Refer friends',
  'logout': 'Logout',
  'refer_us_to_your_friend': 'Refer us to your friend',
  'as_a_thank_you':
      'As a thank you, we’ll give you a big gift when when you invite 5 friends to join the program.',
  'join_now': 'Join Now',
  'change_password': 'Change password',
  'all_tasks': 'All Tasks',
  'video': 'Video',
  'install_app': 'Install App',
  'apply_now': 'Apply Now',
  'detail': 'Chi tiết',
  'used': 'Đã sử dụng',
  'expired': 'Hết hạn',
  'hurray_your_rewards_are_available_now':
      'Hurray! Your rewards are available now.\nLet’s see what you got!',
  'back_to_asset': 'Back to assets',
  'date_of_birth_placeholder': '29221',
  'date_of_birth': 'Date of birth',
  'sex': 'Sex',
  'save': 'Save',
  'edit_profile': 'Edit profile',
  'leave_app': 'Leave app?',
  'change_you_made': 'Changes you made may not be saved.',
  'leave': 'Leave',
  'password_to_secure':
      'Password to secure your account & verify when doing transactions. ',
  'enter_current_password': 'Enter current password',
  'enter_new_password': 'Enter new password',
  'confirm_new_password': 'Comfirm new password',
  'must_match_previous': 'Must match the previous entry',
  'successful': 'SUCCESSFUL',
  'your_password_changed': 'Your password has been changed!',
  'back_to_home': 'Back to Home',
  'back_to_login': 'Back to Login',
  'email_not_found': 'The email you entered is not found',
  'invalid_otp': 'Invalid OTP',
  'no_tray_item': 'You haven’t had any assets yet.',
  'male': 'Nam',
  'female': 'Nữ',
  'other': 'Khác',
  'invalid_credentials': 'Email hoặc mật khẩu không đúng',
  'expiry_date': 'Expiry date: ',
  'please_login_with_social_network': 'Please login with Social Network',
  'no_gift': 'You haven\'t had any Gifts yet',
  'no_used_gifts': 'You haven\'t had any history of used items',
  'no_expired_gifts': 'You haven\'t had any expired items',
  'no_box': 'You haven\'t had any Boxes yet',
  'please_check_your_email_and_confirmation_code_again':
      'Please check your email and confirmation code again',
  'register_failed': 'Register failed',
  'update': 'Cập nhật',
  'task_time_out_title': 'Hết thời gian',
  'task_time_out_content': 'Task của bạn đã hết thời gian',
  'close': 'Đóng',
  'box_is_already_opened': 'This box is already opened',
  'item_has_been_send_to_main_tray': 'The item has been send to main tray',
  'success': 'Thành công',
  'request_location_permission': 'Request location permission',
  'app_collects_location_data':
      'Plats Network app collects location data to provide Checkin Task function',
  'ok': 'Ok',
  'we_have_sent_an_email_please_check_your_email':
      'Chúng tôi đã gửi một email cho bạn. Vui lòng kiểm tra email của bạn',
  'user_cancel_login': 'User cancel login',
  'login_error': 'Login error',
  'others': 'Others',
  'no_items': 'No items',
  'please_check_internet': 'Please check your internet connection',
  'gift': 'Gift',
  'avatar': 'Avatar',
  'take_a_photo': 'Take a photo',
  'choose_from_library': 'Choose from library ',
  'please_enter_your_name': 'Vui lòng nhập tên của bạn',
  'please_wait': 'Vui lòng đợi',
  'your_information_has_been_updated':
      'Your information has been successfully updated.',
  'otp_sent': 'OTP sent',
  'website': 'Website',
  'social': 'Social',
  'description': 'Description',
  'password_validation_not_match': 'Password not matched.',
  'password_validation_8_characters':
      'Password must contain at least eight characters.',
  'password_validation_upper_lower':
      'Password must contain at least one uppercase and one lowercase letter',
  'password_validation_special_character':
      'Password must contain at least one symbol.',
  'password_validation_number': 'Password must contain at least one number.',
  'social_task': 'Social Task',
  'social_tasks': 'Social Tasks',
  'check_in_tasks': 'Check-in Tasks',
  'follow': 'Follow',
  'social_twitter_help_text':
      'Connect your Twitter account to verify Twitter actions in 1 click. \nWe will not post without your permission.',
  'connect_your_twitter_account': 'Connect your Twitter',
  'start_task_success': 'Start task success',
  'twitter_account_connected': 'Twitter account connected',
  'submit': 'Submit',
  'social_task_submit_success': 'Social task submit success',
  'connect_twitter_success': 'Connect Twitter success',
  'connect_twitter_error': 'Twitter id is already used',
  'go_to_assets': 'Go to Assets',
  'task_list': 'Task List',
  'plats_network_points': 'Plats Network Points',
  'delete_account': 'Delete account',
  'delete_account_help_text':
      'Are you sure you want to delete your account?\nThis will permanently delete your account and all of your data. \nYou will not be able to recover your account.',
  'fail_to_delete_account': 'Fail to delete account',
  'PSP': 'PSP',
  'prize': 'Prize',
  'gender': 'Gender',
  'details': 'Details',
  'my_group': 'My Groups',
  'like': 'Like',
  'unlike': 'UnLike',
  'pin': 'Pin',
  'unpin': 'UnPin',
  'share': 'Share',
  'congratulations_you_have_received': 'Congratulations, you’ve got',
};
